"""add plaid fields to linked accounts

Revision ID: 1e9fb585b4ca
Revises: 95b9000208a2
Create Date: 2026-09-09 12:24:36.793010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9fb585b4ca'
down_revision: Union[str, Sequence[str], None] = '95b9000208a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('plaid_item_id', sa.String(length=255), nullable=True))
    op.add_column('linked_accounts', sa.Column('access_token_encrypted', sa.Text(), nullable=True))
    op.create_index(op.f('ix_linked_accounts_plaid_item_id'), 'linked_accounts', ['plaid_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linked_accounts_plaid_item_id'), table_name='linked_accounts')
    op.drop_column('linked_accounts', 'access_token_encrypted')
    op.drop_column('linked_accounts', 'plaid_item_id')
    # ### end Alembic commands ###
