"""add plaid transaction id

Revision ID: b31d9fda54f8
Revises: 1e9fb585b4ca
Create Date: 2026-09-10 07:16:21.993968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31d9fda54f8'
down_revision: Union[str, Sequence[str], None] = '1e9fb585b4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plaid_transaction_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_transactions_plaid_transaction_id'), 'transactions', ['plaid_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_plaid_transaction_id'), table_name='transactions')
    op.drop_column('transactions', 'plaid_transaction_id')
    # ### end Alembic commands ###
